title: Intro to Deep Learning — Term Project
description: Soft-Attention Image Captioning on Flickr8k
remote_theme: yous/whiteglass
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
permalink: /:year/:month/:day/:title/
